FROM gradle:6.9.3-jdk17-alpine as builder
USER root
WORKDIR /builder
ADD . /builder
RUN gradle build --stacktrace

FROM openjdk:17-alpine
WORKDIR /app
EXPOSE 8080
COPY --from=builder /builder/build/libs/avalon-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "avalon-0.0.1-SNAPSHOT.jar"]